type: rpm-ostree
install:
  - bridge-utils      # network bridge for virtualisation
  - vagrant-libvirt   # vagrant install
  - virt-install      # KVM virtualisation
  - virt-manager      # grahical gui for kvm virtualisation
  - edk2-ovmf         # uefi for kvm guests
  - swtpm             # Software TPM for KVM
