type: yafti
custom-flatpaks:
  - Bitwarden: com.bitwarden.desktop                # password tool
  - Foliate: com.github.johnfactotum.Foliate        # ebook reader
  - Mpv: io.mpv.Mpv                                 # movie player
  - Filezilla: org.filezillaproject.Filezilla       # ftp; scp; sftp c
  - MEGAsync: nz.mega.MEGAsync                      # mega client
  - LibreWolf: io.gitlab.librewolf-community        # privacy browser
  - MarkText: com.github.marktext.marktext          # markdown tool
  - FileRoller: org.gnome.FileRoller                # (un)archive app
  - Whalebird: social.whalebird.WhalebirdDesktop    # mastodon client
  - Element: im.riot.Riot                           # element app; mat
  - Cryptomator: org.cryptomator.Cryptomator        # Encryption tool
  - Syncthingy: com.github.zocker_160.SyncThingy    # Syncthingy = Syncthing + tray indicator
