type: rpm-ostree
install:
  - langpacks-en     # English langpacks
  - langpacks-en_GB  # prefered language
  - python3-psutil   # needed for dconf
  - alacritty        # terminal emulator
  - gparted          # partitioning tool
  - gnome-shell-extension-openweather   # OpenWeather Gnome Extension
  - gnome-shell-extension-appindicator  # AppIndicator and KStatusNotifierItem
